GET https://localhost:7020/dinners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhOWEwMjVhZS01MDRhLTRkZDAtODQ2MS01YWM3N2I1ZjdmMWIiLCJnaXZlbl9uYW1lIjoiQW1pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsImp0aSI6IjBjZDU4YjUzLTU1YzgtNGYyOC04M2E2LTEwNTFmNjNhYzI0YyIsImV4cCI6MTY5MzI3NjY5OSwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.4rqK0s6WSNO0UNJjuXiyIhwNDDxkEt-iJPI_PSXNaxs